modLoader="javafml" #mandatory
loaderVersion="[45,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/koratio/issues" #optional
license="All rights reserved"
[[mods]] #mandatory
modId="koratio" #mandatory
version="1.20.1-0.0.1-alpha" #mandatory
displayName="Koratio" #mandatory
#updateJSONURL="https://bitbucket.org/SetroLP/koratio/raw/master/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/koratio" #optional
logoFile="koratio.png" #optional
credits="Test"
authors="Setrion" #optional
description="This mod adds a new Dimension, called Fantasia."
[[dependencies.koratio]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

